### ISSUE TITLE
Exception thrown from AnalysisFilter.ShouldNotAnalyze

### ISSUE THREAD

**Issue by RachelDavids** [RachelDavids/RuleChecker#42]
Severity	Code	Description	Project	File	Line	Suppression State
Error		An uncaught exception occurred. Please file a bug report ( at mailto:rachel.davids@chaucerplc.com )
Rule:	Gendarme.Rules.Maintainability.AvoidExcessiveClassCouplingRule
Target:	Chaucer.Charisma.DB.DatabaseConnection
Stack trace: System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.TypeDefinition' to type 'Mono.Cecil.MethodReference'.
   at Gendarme.Analyzers.Metrics.AnalysisFilter.ShouldNotAnalyze(MemberReference member, FilterOptions options)
   at Gendarme.Analyzers.Metrics.FilterDefaults.CouplingFilter(MemberReference member)
   at Gendarme.Analyzers.Metrics.ClassCoupling`1.AddType(TypeReference type, ISet`1 types)
   at Gendarme.Analyzers.Metrics.ClassCoupling`1.AddTypesForMethod(MethodReference method, ISet`1 types)
   at Gendarme.Analyzers.Metrics.MethodClassCoupling.CoupledClasses()
   at Gendarme.Analyzers.Metrics.TypeClassCoupling.<>c.<CoupledClasses>b__2_1(MethodClassCoupling mcc)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at Gendarme.Analyzers.Metrics.TypeClassCoupling.CoupledClasses()
   at Gendarme.Analyzers.Metrics.TypeClassCoupling.Gendarme.Analyzers.Metrics.IClassMetric<System.Int32>.CoupledClasses()
   at Gendarme.Rules.Maintainability.AvoidExcessiveClassCouplingRule.CheckResults(MemberReference target, IClassMetric`1 x, Int32 higher, Int32 lower)
   at Gendarme.Rules.Maintainability.AvoidExcessiveClassCouplingRule.CheckType(TypeDefinition type)
   at Gendarme.Framework.Runner.OnType(RunnerEventArgs e)
   at Gendarme.Framework.Runner.Run()
   at Gendarme.Tools.Gendarme.ConsoleRunner.Run()
   at Gendarme.Tools.Gendarme.ConsoleRunner.RunAnalysis()
   at Gendarme.Tools.Gendarme.ConsoleRunner.Execute(IEnumerable`1 args)	Charisma.DB	C:\MyData\My Tfs Projects\Charisma\Releases\Charisma\v2.15\Application\packages\Chaucer.CodeAnalysis.Gendarme.16.11.15.1\build\Chaucer.CodeAnalysis.Gendarme.targets	43

**Comment by RachelDavids** [comment]
safe cast introduced ..
